### ISSUE TITLE
YAML serialization can use new `OmitDefaultsOrEmpty`

### ISSUE THREAD

**Issue by premun** [samsmithnz/GitHubActionsDotNet#40]
https://github.com/samsmithnz/GitHubActionsDotNet/blob/aa0f0a196b93835982f97b695734c904bfcf5fbb/src/GitHubActionsDotNet/Serialization/YamlSerialization.cs#L20

I was also serializing pipeline YAML and often had the resulting YAML full of empty arrays, things like:
```yaml
steps: []
```

This is just an FYI that I added functionality there that also omits empty collections. Not sure if you are hitting this but might be of use to you too.

https://github.com/aaubry/YamlDotNet/releases/tag/v11.2.0
https://github.com/aaubry/YamlDotNet/pull/608

**Comment by premun** [comment]
I don't know how you deal with collections but in Sharpliner, I pre-initialize `List<T>` because C# 10 can give you an amazingly brief syntax using the implicit `Add()`.

Say you have this:
```csharp
class SomeClass
{
    List<string> SomeProperty { get; set; } = new();
}
```
then you can do this:
```csharp
var x = new SomeClass
{
    SomeProperty = {
        "foo",
        "bar",
    }
}
```

However, this implicit `Add` only works if the `List<T>` property is non-null and initialized. Just calls `Add` on it.

Now, let's say you have pipeline triggers and want to use this - this means your `Trigger` property on the pipeline needs to be an initialized list but you don't really want your YAML to be always:
```yaml
triggers: []
```

You only want triggers to be serialized when it's not empty.

Now, I don't know GH Actions much so I don't know if you have problems like this. Or you might just have `null` values for your Lists. Then you can disregard this :)

**Comment by premun** [comment]
Btw I reached out to you in a more reasonable manner on Teams but I guess you're off already (I didn't mean to ambush you here like this)

**Comment by samsmithnz** [comment]
I'm pretty sure that `triggers: []` is valid, just ugly, as [YAML is a superset of JSON](https://stackoverflow.com/questions/1726802/what-is-the-difference-between-yaml-and-json). I think you can get around this by either not initializing the list, or using an array (with no items).
